name: Android APK Build

on:
  push:
    branches:
      - main # or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Use a stable Node.js version

    - name: Install Cordova CLI
      run: npm install -g cordova

    - name: Install dependencies (plugins)
      run: npm install # This will install plugins from package.json if present

    - name: Add Android platform
      # Use --no-save to prevent modifying package.json and config.xml unnecessarily on CI
      # And only if platforms/android doesn't already exist from a previous step (unlikely on fresh runner)
      run: |
        if [ ! -d "platforms/android" ]; then
          cordova platform add android --no-save
        else
          echo "Android platform already added."
        fi

    - name: Build Android release APK
      run: cordova build android --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk # Corrected filename
